### ISSUE TITLE
make docs in Vagrant fails

### ISSUE THREAD

**Issue by tomgross** [plone/mockup#497]
The command `make docs` in a current checkout 1623c30fd4f5694f2873c4bd7d6b18bca5a90b91 fails with 

```
vagrant@mockup:~$ cd /vagrant/
vagrant@mockup:/vagrant$ make docs
rm -Rf mockup/docs; mkdir mockup/docs; cp -R .git mockup/docs; cd mockup/docs; git checkout gh-pages;
Checking out files: 100% (5004/5004), done.
Branch gh-pages set up to track remote branch gh-pages from origin.
Switched to a new branch 'gh-pages'
# if test ! -d mockup/docs; then git clone git://github.com/plone/mockup.git -b gh-pages mockup/docs; fi
rm -rf mockup/docs/dev
NODE_PATH=./node_modules ./node_modules/grunt-cli/bin/grunt bundle-docs   --gruntfile=mockup/Gruntfile.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/node_modules/grunt-cli/bin/grunt:8:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
make: *** [docs] Error 8
```

**Comment by tomgross** [comment]
It seems like a problem with missing dependencies:
http://stackoverflow.com/questions/15444020/cannot-find-module-findup-sync-when-trying-to-run-grunt

resolve
findup-sync
coffee-script
...

**Comment by vangheem** [comment]
If you add those missing dependencies, it works?

**Comment by tomgross** [comment]
It goes further but I stoped trying at some point.

**Comment by jensens** [comment]
Closing as outdated. Mockup was completely rewritten for Plone 6 (jQuery/Backbone/RequireJS → ES6/Patternslib). make docs in Vagrant fails.
If you think this issue is still relevant in the new implementation, please reopen it. Thank you for the original report!
